import type { MountlyManifest } from "./schema.js";
import { verticalImportEntries } from "./resolve.js";

export interface CodegenOptions {
  /** Emit `declare module` blocks with a generic namespace export. */
  moduleExport?: "namespace" | "any";
  /**
   * Resolve a local declaration module path for a manifest remote specifier.
   * When present, generated modules re-export real remote declaration files instead of `unknown`.
   */
  resolveDeclarationModule?: (args: {
    vertical: MountlyManifest["verticals"][number];
    specifier: string;
    exportKey?: string;
  }) => string | null;
  /** Override export names when generating explicit re-exports for declaration modules. */
  resolveExportNames?: (args: {
    vertical: MountlyManifest["verticals"][number];
    specifier: string;
    exportKey?: string;
  }) => string[];
}

/**
 * Generate ambient TypeScript declarations for manifest remote specifiers so Vite hosts
 * can `import('payments/Checkout')` with type-checking.
 */
export function codegenManifestTypes(
  manifest: MountlyManifest,
  options: CodegenOptions = {},
): string {
  const mode = options.moduleExport ?? "namespace";
  const lines: string[] = ["// Generated by mountly manifest codegen — do not edit.", ""];

  for (const vertical of manifest.verticals) {
    const rootNames = new Set(vertical.types?.module ?? []);
    if (vertical.featureExport) rootNames.add(vertical.featureExport);

    for (const { specifier } of verticalImportEntries(vertical)) {
      const rootSpecifier = vertical.alias ?? vertical.id;
      const exportKey =
        specifier === rootSpecifier ? undefined : `./${specifier.slice(rootSpecifier.length + 1)}`;
      const declarationModule = options.resolveDeclarationModule?.({
        vertical,
        specifier,
        exportKey,
      });
      const names =
        options.resolveExportNames?.({ vertical, specifier, exportKey }) ??
        (specifier === rootSpecifier
          ? [...rootNames]
          : extractExportNames(vertical.types?.exports?.[exportKey as string]));

      lines.push(`declare module "${specifier}" {`);
      if (declarationModule) {
        if (names.length > 0) {
          for (const name of names) {
            lines.push(`  export { ${name} } from ${JSON.stringify(declarationModule)};`);
          }
        } else {
          lines.push(`  export * from ${JSON.stringify(declarationModule)};`);
        }
        lines.push(`  const mod: typeof import(${JSON.stringify(declarationModule)});`);
      } else if (mode === "any") {
        lines.push("  const mod: unknown;");
      } else if (names.length > 0) {
        for (const name of names) {
          lines.push(`  export const ${name}: unknown;`);
        }
        lines.push("  const mod: {");
        for (const name of names) {
          lines.push(`    readonly ${name}: typeof ${name};`);
        }
        lines.push("  } & Record<string, unknown>;");
      } else {
        lines.push("  const mod: Record<string, unknown>;");
      }
      lines.push("  export default mod;");
      lines.push("}");
      lines.push("");
    }
  }

  return lines.join("\n").trimEnd() + "\n";
}

function extractExportNames(
  value:
    | string[]
    | {
        declaration?: string;
        names?: string[];
      }
    | undefined,
): string[] {
  if (!value) return [];
  return Array.isArray(value) ? value : (value.names ?? []);
}
